---
- name: install python2
  yum:
    name: python2
    update_cache: yes
    state: "{{docker_py_python2_state|default(omit)}}"
- name: install pip
  yum:
    name: python2-pip
    update_cache: yes
    state: "{{docker_py_pip_state|default(omit)}}"
- name: install docker-py
  pip:
    name: docker-py
    state: "{{docker_py_docker_py_state|default(omit)}}"
